services:
  branch-environment-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  pgsql:
    image: "docker.io/library/postgres:17.6"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "x39.software.exammaker.apphost-add39866f1-pgsql-data"
        read_only: false
    networks:
      - "aspire"
  api:
    image: "${API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${API_PORT}"
      ConnectionStrings__auth-db: "Host=pgsql;Port=5432;Username=postgres;Password=${PGSQL_PASSWORD};Database=auth-db"
      AUTH_DB_HOST: "pgsql"
      AUTH_DB_PORT: "5432"
      AUTH_DB_USERNAME: "postgres"
      AUTH_DB_PASSWORD: "${PGSQL_PASSWORD}"
      AUTH_DB_URI: "postgresql://postgres:${PGSQL_PASSWORD}@pgsql:5432/auth-db"
      AUTH_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://pgsql:5432/auth-db"
      AUTH_DB_DATABASENAME: "auth-db"
      ConnectionStrings__exam-db: "Host=pgsql;Port=5432;Username=postgres;Password=${PGSQL_PASSWORD};Database=exam-db"
      EXAM_DB_HOST: "pgsql"
      EXAM_DB_PORT: "5432"
      EXAM_DB_USERNAME: "postgres"
      EXAM_DB_PASSWORD: "${PGSQL_PASSWORD}"
      EXAM_DB_URI: "postgresql://postgres:${PGSQL_PASSWORD}@pgsql:5432/exam-db"
      EXAM_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://pgsql:5432/exam-db"
      EXAM_DB_DATABASENAME: "exam-db"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://branch-environment-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "api"
    expose:
      - "${API_PORT}"
    depends_on:
      pgsql:
        condition: "service_started"
    networks:
      - "aspire"
  app:
    image: "${APP_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${APP_PORT}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://branch-environment-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "app"
    expose:
      - "${APP_PORT}"
    depends_on:
      api:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  x39.software.exammaker.apphost-add39866f1-pgsql-data:
    driver: "local"
